name: orthanq
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - coincbc
  - gcc_linux-64
  - pkg-config
  - gsl =2.7
  - cmake
  - ncbi-datasets-cli=16.4.4
  - seqtk
  - samtools=1.17
  - varlociraptor=8.4.7
  - vg=1.50.1
  - minimap2=2.24
  - bwa=0.7.17
  - htslib
